const STORAGE_KEY = 'badaHansang.sharedData.v1';
const seedBoats = [
  {id:'blue-sea',name:'푸른바다호',fisher:'김선장',port:'통영 · 욕지도',catch:'참돔 · 전갱이',icon:'⛵',logs:[{date:'2026. 07. 28.',title:'참돔 42kg · 전갱이 31kg',text:'동풍이 약해 욕지도 인근에서 안정적으로 조업 중입니다.',photos:[]}],products:[{id:'p1',name:'활참돔 1kg',price:28000,quantity:14,description:'오늘 선별한 활참돔입니다.',photo:''},{id:'p2',name:'전갱이 1kg',price:12000,quantity:20,description:'통영 연안에서 잡은 전갱이입니다.',photo:''}]},
  {id:'sunrise',name:'해맞이호',fisher:'박선장',port:'제주 · 성산',catch:'갈치 · 고등어',icon:'🛥️',logs:[{date:'2026. 07. 28.',title:'갈치 35kg · 고등어 60kg',text:'성산 앞바다에서 조업을 시작했습니다.',photos:[]}],products:[{id:'p3',name:'제주 은갈치 500g',price:24000,quantity:12,description:'제주 성산 앞바다 은갈치입니다.',photo:''}]},
  {id:'sea-star',name:'바다별호',fisher:'이선장',port:'여수 · 돌산',catch:'문어 · 갑오징어',icon:'🚤',logs:[{date:'2026. 07. 28.',title:'문어 18kg · 갑오징어 29kg',text:'돌산 연안 수온이 좋아 조업을 이어갑니다.',photos:[]}],products:[{id:'p4',name:'돌문어 500g',price:31000,quantity:8,description:'여수 돌산에서 잡은 문어입니다.',photo:''}]}
];
const screen = document.querySelector('#screen');
const modalLayer = document.querySelector('#modal-layer');
let investmentCarouselTimer = null;
const today = () => new Date().toLocaleDateString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit'}).replace(/\. /g,'. ').replace(/\.$/,'')+'.';
function db(){let raw=localStorage.getItem(STORAGE_KEY);let data;if(raw){data=JSON.parse(raw)}else{data={boats:seedBoats,supports:{},accounts:[],currentAccountId:null,fisherBoatId:null,posts:[]}}if(!data.accounts){data.accounts=[];if(data.fisherBoatId){const legacyBoat=data.boats.find(b=>b.id===data.fisherBoatId);if(legacyBoat){const legacyId='account-legacy';data.accounts.push({id:legacyId,name:legacyBoat.fisher||'기존 어부',password:'',boatId:legacyBoat.id});legacyBoat.accountId=legacyId;data.currentAccountId=legacyId}data.fisherBoatId=null}}if((data.schemaVersion||0)<9){const deletedIds=new Set((data.boats||[]).filter(b=>b.accountId||String(b.id).startsWith('my-boat-')).map(b=>b.id));data.boats=(data.boats||[]).filter(b=>!deletedIds.has(b.id));Object.keys(data.supports||{}).forEach(id=>{if(deletedIds.has(id))delete data.supports[id]});data.accounts=[];data.currentAccountId=null;data.fisherBoatId=null;data.schemaVersion=9}if(!data.posts)data.posts=[];save(data);return data}
function save(data){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function boat(id){return db().boats.find(x=>x.id===id)}
function money(n){return `${Number(n).toLocaleString('ko-KR')}원`}
function back(title,target='start'){return `<div class="title-row"><button class="back" data-go="${target}">‹</button><h1>${title}</h1></div>`}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}

function startInvestmentCarousel(){clearInterval(investmentCarouselTimer);let index=0;investmentCarouselTimer=setInterval(()=>{const carousel=document.querySelector('.investment-carousel');if(!carousel){clearInterval(investmentCarouselTimer);return}const cards=carousel.querySelectorAll('.investment-card');if(!cards.length)return;index=(index+1)%cards.length;carousel.scrollTo({left:index*(cards[0].offsetWidth+12),behavior:'smooth'})},1000)}
function viewHome(){const data=db(),ranked=data.boats.slice().sort((a,b)=>(data.supports[b.id]||0)-(data.supports[a.id]||0)).slice(0,3),feed=data.boats.flatMap(b=>b.logs.map(l=>({boat:b,log:l}))).slice().reverse().slice(0,5);screen.innerHTML=`<section class="ocean-home"><div class="ocean-home-copy"><small>피시 펀딩 · 오늘의 바다</small><h1>오늘의 바다<br><em>한 스푼</em></h1><p>바다의 온도를 느끼고, 신선함에 투자하세요.</p></div><span class="home-boat">⛵</span></section><section class="sea-report"><div class="report-title"><span>🌤️</span><div><small>오늘의 바다 한 스푼</small><strong>맑음 · 잔잔한 파도</strong></div><b>통영</b></div><div class="report-stats"><div><span>파도 높이</span><strong>0.4m</strong></div><div><span>바다 상태</span><strong>매우 좋음</strong></div><div><span>수온</span><strong>23°C</strong></div></div><p>부드러운 바람과 잔잔한 물결, 오늘은 조업하기 좋은 날이에요.</p><article class="season-card"><span>🦪</span><div><small>오늘의 제철 해산물</small><strong>통영 생굴</strong><p>바다 향이 가득한, 지금 가장 맛있는 제철 한입</p></div></article></section><section class="home-section"><div class="home-section-title"><h2>인기 투자</h2><span>1초마다 자동으로 바뀌어요</span></div><div class="investment-carousel">${ranked.map((b,i)=>`<article class="investment-card"><div class="investment-picture">${b.icon||'⚓'}</div><small>${i===0?'이번 주 1위':'인기 어선'}</small><h3>${b.name}</h3><p>${b.fisher} 선장 · ${b.catch}</p><strong>💙 ${money(data.supports[b.id]||0)}</strong></article>`).join('')}<article class="investment-card farm-card"><div class="investment-picture">🦪</div><small>인기 양식장</small><h3>청정바다 굴 양식장</h3><p>통영 연안 · 제철 생굴</p><strong>💙 1,240,000원</strong></article></div></section><section class="home-section feed-section"><div class="home-section-title"><h2>어민 현장 피드</h2><span>오늘의 바다 이야기</span></div><div class="field-feed">${feed.length?feed.map(({boat:b,log:l})=>`<article class="feed-card"><div class="feed-head"><span>${b.icon||'⚓'}</span><div><strong>${b.name}</strong><small>${l.date} · ${b.fisher} 선장</small></div></div>${l.photos?.length?`<img src="${l.photos[0]}" alt="${b.name} 조업 현장">`:`<div class="feed-fallback">${b.icon||'⚓'}<span>오늘의 조업 현장</span></div>`}<h3>${l.title}</h3><p>${l.text}</p></article>`).join(''):`<article class="feed-card"><div class="feed-fallback">🌊<span>어민의 첫 현장 기록을 기다리고 있어요</span></div></article>`}</div></section><button class="community-entry" data-go="community"><span>💬</span><div><strong>커뮤니티</strong><small>어민과 소비자가 나누는 바다 이야기</small></div><i>›</i></button><button class="invest-fab" data-go="role-select">＋ <span>로그인하기</span></button>`;startInvestmentCarousel()}
function viewRoleSelect(){screen.innerHTML=back('피시 펀딩 시작')+`<section class="home-hero role-hero"><small>바다를 함께 키우는 방법</small><h1>어떤 방식으로<br>바다와 함께할까요?</h1><p>응원자는 신선한 수산물을 받고, 어부는 오늘의 바다를 기록합니다.</p></section><section class="home-actions"><button class="action-card" data-go="support-home"><b>💙</b><span><strong>응원자</strong>어선을 응원하고 산지 직송 수산물을 만나보세요.</span><i>›</i></button><button class="action-card my" data-go="fisher-entry"><b>⚓</b><span><strong>어부</strong>조업을 기록하고 수산물을 판매해 보세요.</span><i>›</i></button></section>`}
function viewSupportHome(){screen.innerHTML=back('응원자')+`<section class="home-hero"><small>오늘의 바다를 함께 키워요</small><h1>바다의 하루가<br>당신의 식탁으로</h1><p>어선을 응원하고, 오늘 잡은 신선한 수산물을 직접 받아보세요.</p></section><section class="home-actions"><button class="action-card" data-go="boats"><b>⛵</b><span><strong>어선 목록 보기</strong>어선별 주요 어획물과 조업 일지를 살펴보세요.</span><i>›</i></button><button class="action-card my" data-go="my-boats"><b>🌊</b><span><strong>내 어선 현황 보기</strong>내가 응원한 어선과 받을 수산물을 확인하세요.</span><i>›</i></button></section>`}
function boatCard(b, mine=false){const support=db().supports[b.id]||0, latest=b.logs.at(-1);return `<article class="boat-card"><div class="boat-icon">${b.icon||'⚓'}</div><div><div class="boat-top"><span>${b.port||'등록 어선'}</span><b class="status">${b.logs.length?'일지 업데이트':'조업 준비'}</b></div><h2>${b.name}</h2><p class="catch">${b.fisher} 선장 · ${b.catch||'어획물 정보 미등록'}</p>${mine&&latest?`<p class="latest-log">최신 조업 · ${latest.date} · ${latest.title}</p>`:''}<div class="boat-foot"><span>${mine?`누적 응원금 ${money(support)} · 판매 ${b.products.length}종`:`판매 수산물 ${b.products.length}종`}</span><div class="card-buttons">${mine?`<button class="support-button" data-detail="${b.id}">내 어선 보기</button>`:`<button class="log-button" data-public-log="${b.id}">조업 일지</button><button class="log-button" data-public-products="${b.id}">수산물</button><button class="support-button" data-support="${b.id}">응원하기</button>`}</div></div></div></article>`}
function viewBoats(){const data=db();screen.innerHTML=back('어선 목록','support-home')+`<p class="subtitle">좌우로 밀어 여러 어선을 살펴보세요. 조업 일지와 판매 수산물도 바로 확인할 수 있어요.</p><section class="boat-list draggable-list">${data.boats.map(b=>boatCard(b)).join('')}</section>`}
function viewMyBoats(){const data=db(), mine=data.boats.filter(b=>(data.supports[b.id]||0)>0);screen.innerHTML=back('내 어선 현황','support-home')+(mine.length?`<p class="subtitle">응원한 어선을 선택해 조업 일지와 산지 직송 상품을 확인하세요.</p><section class="boat-list">${mine.map(b=>boatCard(b,true)).join('')}</section>`:`<section class="empty"><b>🌊</b><h2>아직 응원한 어선이 없어요</h2><p>마음에 드는 어선을 응원하면<br>이곳에서 조업 현황을 확인할 수 있어요.</p><button class="primary-button" data-go="boats">어선 목록 보기</button></section>`)}
function viewSupportDetail(id){const b=boat(id), amount=db().supports[id]||0;screen.innerHTML=back(b.name,'my-boats')+`<section class="detail-hero"><small>${b.port||'등록 어선'} · ${b.fisher} 선장</small><h2>${b.icon||'⚓'} ${b.name}</h2><p>주요 어획물 · ${b.catch||'정보 등록 전'}</p></section><section class="info-box"><span>내 누적 응원금</span><strong>${money(amount)}</strong></section><section class="detail-actions"><button class="outline-button" data-log="${id}" data-back="my-boats">조업 일지 보기</button><button class="primary-button" data-products="${id}">수산물 받기</button></section>`}
function viewLogs(id, backTo='support-detail'){const b=boat(id);screen.innerHTML=back(`${b.name} 조업 일지`,backTo)+`<p class="subtitle">${b.fisher} 선장이 직접 기록한 조업 상황입니다.</p><section class="log">${b.logs.length?b.logs.slice().reverse().map(l=>`<article class="log-item"><small>${l.date}</small><h3>${l.title||'오늘의 조업 기록'}</h3><p>${l.text}</p>${l.photos?.length?`<div class="photo-row">${l.photos.map(p=>`<img src="${p}" alt="조업 사진">`).join('')}</div>`:''}</article>`).join(''):`<section class="empty"><b>📝</b><h2>아직 작성된 조업 일지가 없어요</h2><p>선장이 첫 조업 기록을 남기면 이곳에 표시됩니다.</p></section>`}</section>`}
function viewProducts(id,backTo='my-boats'){const b=boat(id);screen.innerHTML=back('수산물 받기',backTo)+`<p class="subtitle">${b.name}에서 판매 중인 산지 직송 수산물입니다.</p>${b.products.length?`<section class="product-list">${b.products.map((p,i)=>`<label class="product"><input type="radio" name="product" value="${p.id}" ${i===0?'checked':''}><span class="product-photo">${p.photo?`<img src="${p.photo}" alt="${p.name}">`:'🦪'}</span><span><strong>${p.name}</strong><span>${money(p.price)} · ${p.quantity}개 남음</span></span></label>`).join('')}</section><div class="delivery">지금 신청하면 선별·포장 후 <b>내일 오후 1~6시</b> 배송 예정입니다.</div><button class="primary-button full" data-delivery="${id}">직송받기</button>`:`<section class="empty"><b>🧺</b><h2>판매 중인 수산물이 없어요</h2><p>선장이 상품을 등록하면 이곳에 표시됩니다.</p></section>`}`}
function openSupport(id){const b=boat(id);modalLayer.hidden=false;modalLayer.innerHTML=`<section class="modal"><h2>${b.name} 응원하기</h2><p>응원금은 유류비, 얼음, 어구 같은 조업 기본 비용에 쓰입니다.</p><input id="support-amount" class="amount-input" type="number" inputmode="numeric" min="10000" step="1000" placeholder="10,000원 이상 입력"><div class="amount-help" id="amount-help"></div><div class="modal-actions"><button class="cancel" data-close>취소</button><button class="primary-button" data-confirm-support="${id}">응원 완료</button></div></section>`}

function activeAccount(){const data=db();return data.accounts.find(a=>a.id===data.currentAccountId)}
function activeBoat(data=db()){const account=data.accounts.find(a=>a.id===data.currentAccountId);return account&&data.boats.find(b=>b.id===account.boatId)}
function viewFisherEntry(){const data=db();if(data.currentAccountId){viewFisherHome();return}viewLogin()}
function viewLogin(){screen.innerHTML=back('어부 로그인')+`<p class="subtitle">처음이라면 입력한 정보로 계정과 어선이 등록됩니다. 기존 계정은 세 정보가 모두 일치해야 로그인됩니다.</p><form class="form-card" id="login-form"><label>어선 이름<input name="boatName" required placeholder="예: 바다희망호"></label><label>어부 이름<input name="fisherName" required placeholder="예: 홍길동"></label><label>비밀번호<input name="password" type="password" required placeholder="비밀번호 입력"></label><button class="primary-button full" type="submit">로그인 / 최초 등록</button></form>`}
function viewFisherHome(){const b=activeBoat();if(!b){const data=db();data.currentAccountId=null;save(data);viewFisherEntry();return}screen.innerHTML=back('어부')+`<section class="fisher-banner"><small>등록 어선</small><h2>${b.icon||'⚓'} ${b.name}</h2><p>${b.fisher} 선장 · ${b.catch||'주요 어획물 미등록'}</p></section><section class="fisher-actions"><button class="action-card" data-go="write-log"><b>📝</b><span><strong>조업 일지 쓰기</strong>오늘의 어획과 조업 상황을 사진과 함께 기록하세요.</span><i>›</i></button><button class="action-card my" data-go="funds"><b>💰</b><span><strong>응원금 보기</strong>응원자가 보낸 누적 응원금을 확인하세요.</span><i>›</i></button><button class="action-card sell" data-go="sell"><b>🧺</b><span><strong>수산물 팔기</strong>산지 직송할 수산물을 등록하고 판매하세요.</span><i>›</i></button><button class="logout-button" data-logout>로그아웃</button></section>`}
function viewWriteLog(){screen.innerHTML=back('조업 일지 쓰기','fisher-home')+`<p class="subtitle">작성 날짜는 자동으로 기록되며, 등록 즉시 응원자 화면에도 반영됩니다.</p><form class="form-card" id="log-form"><label>오늘의 어획량 / 제목<input name="title" required placeholder="예: 고등어 30kg · 오징어 12kg"></label><label>조업 상황<textarea name="text" required placeholder="오늘의 날씨, 조업 위치, 어획 상황을 자유롭게 작성하세요."></textarea></label><label>조업 사진 <input name="photos" type="file" accept="image/*" multiple><small>여러 장 선택할 수 있습니다.</small></label><button class="primary-button full" type="submit">작성 완료</button></form>`}
function viewFunds(){const data=db(), b=activeBoat(data), amount=data.supports[b.id]||0;screen.innerHTML=back('응원금 보기','fisher-home')+`<section class="fund-card"><span>${b.name}에 도착한 누적 응원금</span><strong>${money(amount)}</strong><p>응원자가 보낸 금액이 저장 즉시 자동으로 반영됩니다.</p></section>`}
function viewSell(){const b=activeBoat();screen.innerHTML=back('수산물 팔기','fisher-home')+`<p class="subtitle">등록한 상품은 응원자 화면의 ‘수산물 받기’에 즉시 표시됩니다.</p><form class="form-card" id="product-form"><label>수산물 이름<input name="name" required placeholder="예: 손질 고등어 1kg"></label><div class="form-grid"><label>가격(원)<input name="price" type="number" min="0" required placeholder="15000"></label><label>수량<input name="quantity" type="number" min="1" required placeholder="10"></label></div><label>상품 설명<textarea name="description" required placeholder="상품 상태와 구성 등을 적어 주세요."></textarea></label><label>상품 사진<input name="photo" type="file" accept="image/*"><small>사진 1장을 등록할 수 있습니다.</small></label><button class="primary-button full" type="submit">🧺 판매 상품 등록</button></form><section class="mini-list"><h2>판매 목록 (${b.products.length})</h2>${b.products.map(p=>`<article class="sell-product-card"><span class="sell-product-image">${p.photo?`<img src="${p.photo}" alt="${p.name}">`:'🦪'}</span><span><strong>${p.name}</strong><small>${p.description||'산지 직송 상품'}</small><b>${money(p.price)} · ${p.quantity}개</b></span></article>`).join('')||'<p>아직 등록한 상품이 없습니다.</p>'}</section>`}
function postCard(p){return `<article class="post-card"><div class="post-head"><span>${p.category==='recipe'?'🍳':p.category==='review'?'⭐':'💬'}</span><div><strong>${p.author}</strong><small>${p.date} · ${p.category==='recipe'?'수산물 레시피':p.category==='review'?'구매 후기':'소통 게시판'}</small></div>${p.rating?`<b>${'★'.repeat(p.rating)}${'☆'.repeat(5-p.rating)}</b>`:''}</div>${p.photo?`<img src="${p.photo}" alt="게시글 사진">`:''}<h3>${p.title}</h3><p>${p.content}</p><div class="post-actions"><button data-like="${p.id}">♡ ${p.likes||0}</button><button data-post-detail="${p.id}">💬 ${(p.comments||[]).length}</button></div></article>`}
function viewCommunity(tab='talk'){const data=db(),posts=data.posts.filter(p=>p.category===tab).slice().reverse();screen.innerHTML=back('커뮤니티')+`<p class="subtitle">어민과 소비자가 함께 만드는 바다 이야기입니다.</p><div class="community-tabs"><button class="${tab==='talk'?'selected':''}" data-community-tab="talk">💬 소통</button><button class="${tab==='recipe'?'selected':''}" data-community-tab="recipe">🍳 레시피</button><button class="${tab==='review'?'selected':''}" data-community-tab="review">⭐ 후기</button></div><button class="write-post" data-write-post="${tab}">✏️ ${tab==='recipe'?'레시피':'게시글'} 작성</button><section class="post-list">${posts.length?posts.map(postCard).join(''):`<section class="empty"><b>${tab==='recipe'?'🍳':tab==='review'?'⭐':'💬'}</b><h2>아직 게시글이 없어요</h2><p>첫 번째 이야기를 남겨 보세요.</p></section>`}</section>`}
function viewWritePost(category){const label=category==='recipe'?'수산물 레시피':category==='review'?'구매 후기':'소통 게시글';screen.innerHTML=back(`${label} 작성`,'community')+`<form class="form-card" id="post-form"><input type="hidden" name="category" value="${category}"><label>작성자<input name="author" required placeholder="닉네임을 입력하세요"></label><label>제목<input name="title" required placeholder="제목을 입력하세요"></label>${category==='review'?`<label>별점<select name="rating"><option value="5">★★★★★ (5점)</option><option value="4">★★★★☆ (4점)</option><option value="3">★★★☆☆ (3점)</option><option value="2">★★☆☆☆ (2점)</option><option value="1">★☆☆☆☆ (1점)</option></select></label>`:''}<label>${category==='recipe'?'레시피 내용':'내용'}<textarea name="content" required placeholder="${category==='recipe'?'재료와 조리 방법을 자유롭게 작성하세요.':'조업 이야기, 응원 메시지, 질문을 자유롭게 남겨 주세요.'}"></textarea></label><label>사진<input name="photo" type="file" accept="image/*"><small>사진 1장을 함께 올릴 수 있습니다.</small></label><button class="primary-button full" type="submit">등록하기</button></form>`}
function viewPostDetail(id){const p=db().posts.find(x=>x.id===id);screen.innerHTML=back('게시글', 'community')+`<section class="post-list">${postCard(p)}</section><section class="comment-box"><h2>댓글 ${(p.comments||[]).length}</h2>${(p.comments||[]).map(c=>`<article><strong>${c.author}</strong><small>${c.date}</small><p>${c.text}</p></article>`).join('')||'<p class="no-comment">첫 댓글을 남겨 보세요.</p>'}<form id="comment-form"><input type="hidden" name="postId" value="${p.id}"><input name="author" required placeholder="닉네임"><input name="text" required placeholder="댓글을 입력하세요"><button type="submit">등록</button></form></section>`}

async function filesToData(files){return Promise.all([...files].map(f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)})))}
screen.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;const go=t.dataset.go;if(go==='start')viewHome();if(go==='community')viewCommunity();if(go==='role-select')viewRoleSelect();if(go==='support-home')viewSupportHome();if(go==='boats')viewBoats();if(go==='my-boats')viewMyBoats();if(go==='fisher-entry')viewFisherEntry();if(go==='fisher-home')viewFisherHome();if(go==='login')viewLogin();if(go==='write-log')viewWriteLog();if(go==='funds')viewFunds();if(go==='sell')viewSell();if(t.dataset.communityTab)viewCommunity(t.dataset.communityTab);if(t.dataset.writePost)viewWritePost(t.dataset.writePost);if(t.dataset.postDetail)viewPostDetail(t.dataset.postDetail);if(t.dataset.like){const data=db(),p=data.posts.find(x=>x.id===t.dataset.like);p.likes=(p.likes||0)+1;save(data);viewCommunity(p.category)}if(t.hasAttribute('data-logout')){const data=db();data.currentAccountId=null;save(data);toast('로그아웃되었습니다.');viewFisherEntry()}if(t.dataset.support)openSupport(t.dataset.support);if(t.dataset.detail)viewSupportDetail(t.dataset.detail);if(t.dataset.log)viewLogs(t.dataset.log,t.dataset.back||'support-detail');if(t.dataset.publicLog)viewLogs(t.dataset.publicLog,'boats');if(t.dataset.products)viewProducts(t.dataset.products);if(t.dataset.publicProducts)viewProducts(t.dataset.publicProducts,'boats');if(t.dataset.delivery){const b=boat(t.dataset.delivery), pid=document.querySelector('input[name="product"]:checked').value,p=b.products.find(x=>x.id===pid);toast(`${p.name} 직송 신청이 완료됐어요. 내일 배송 예정입니다.`)}});
screen.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,data=db(), values=new FormData(form);if(form.id==='post-form'){const files=form.elements.photo.files,photo=files.length?(await filesToData(files))[0]:'';data.posts.push({id:'post-'+Date.now(),category:values.get('category'),author:values.get('author'),title:values.get('title'),content:values.get('content'),rating:Number(values.get('rating')||0),photo,likes:0,comments:[],date:today()});save(data);toast('게시글이 등록되었습니다.');viewCommunity(values.get('category'));return}if(form.id==='comment-form'){const p=data.posts.find(x=>x.id===values.get('postId'));p.comments.push({author:values.get('author'),text:values.get('text'),date:today()});save(data);toast('댓글이 등록되었습니다.');viewPostDetail(p.id);return}if(form.id==='login-form'){const boatName=values.get('boatName').trim(),fisherName=values.get('fisherName').trim(),password=values.get('password'),existingBoat=data.boats.find(b=>b.name===boatName&&b.fisher===fisherName),existingAccount=existingBoat&&data.accounts.find(a=>a.boatId===existingBoat.id);if(existingAccount){if(existingAccount.password!==password){toast('비밀번호가 올바르지 않습니다.');return}data.currentAccountId=existingAccount.id;save(data);toast(`${fisherName}님, 다시 오셨네요.`);viewFisherHome();return}if(data.boats.some(b=>b.name===boatName)||data.accounts.some(a=>a.name===fisherName)){toast('이미 사용 중인 어선 이름 또는 어부 이름입니다.');return}const accountId='account-'+Date.now(),boatId='my-boat-'+Date.now();data.boats.push({id:boatId,accountId,name:boatName,fisher:fisherName,catch:'어획물 정보 미등록',port:'내 등록 어선',icon:'⚓',logs:[],products:[]});data.accounts.push({id:accountId,name:fisherName,password,boatId});data.currentAccountId=accountId;save(data);toast('최초 등록과 로그인이 완료됐습니다.');viewFisherHome()}if(form.id==='log-form'){const b=activeBoat(data), photos=await filesToData(form.elements.photos.files);b.logs.push({date:today(),title:values.get('title'),text:values.get('text'),photos});save(data);toast('조업 일지가 등록되었습니다.');viewFisherHome()}if(form.id==='product-form'){const b=activeBoat(data), photoFiles=form.elements.photo.files, photo=photoFiles.length?(await filesToData(photoFiles))[0]:'';b.products.push({id:'product-'+Date.now(),name:values.get('name'),price:Number(values.get('price')),quantity:Number(values.get('quantity')),description:values.get('description'),photo});save(data);toast('판매 상품이 등록되었습니다.');viewSell()}});
modalLayer.addEventListener('click',e=>{if(e.target===modalLayer||e.target.closest('[data-close]')){modalLayer.hidden=true;return}const t=e.target.closest('[data-confirm-support]');if(!t)return;const amount=Number(document.querySelector('#support-amount').value),help=document.querySelector('#amount-help');if(!amount||amount<10000){help.textContent='응원금은 10,000원 이상 입력해 주세요.';return}const data=db(),id=t.dataset.confirmSupport;data.supports[id]=(data.supports[id]||0)+amount;save(data);modalLayer.hidden=true;toast(`${boat(id).name} 응원이 완료됐어요.`);viewMyBoats()});
new MutationObserver(()=>{screen.classList.remove('screen-in');requestAnimationFrame(()=>screen.classList.add('screen-in'))}).observe(screen,{childList:true});
window.addEventListener('storage',event=>{if(event.key===STORAGE_KEY)viewHome()});
document.querySelector('#home-button').addEventListener('click',viewHome);viewHome();
